//////////////////////////////
//  Oak Editor Drag and Drop setup for HTML elements.
//  Dictates which components can be dropped where, etc.
//
//  TODO: SVG elements???
//  TODO: See https://github.com/facebook/react/blob/master/src/renderers/dom/client/validateDOMNesting.js
//
//////////////////////////////

import EditorProps from "../oak/EditorProps";

// SEE:  https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories
export default {
  "a": new EditorProps({ droppable: true, dragType:"a"}),
  "abbr": new EditorProps({ droppable: true, dragType:"abbr"}),
  "address": new EditorProps({ droppable: true, dragType:"address"}),
  "area": new EditorProps({ dragType:"area"}),
  "article": new EditorProps({ droppable: true, dragType:"article"}),
  "aside": new EditorProps({ droppable: true, dragType:"aside"}),
  "audio": new EditorProps({ droppable: true, dropTypes: "source", dragType:"audio"}),
  "b": new EditorProps({ droppable: true, dragType:"b"}),
  "base": new EditorProps({ dragType:"base"}),
  "bdi": new EditorProps({ droppable: true, dragType:"bdi"}),
  "bdo": new EditorProps({ droppable: true, dragType:"bdo"}),
  "big": new EditorProps({ droppable: true, dragType:"big"}),
  "blockquote": new EditorProps({ droppable: true, dragType:"blockquote"}),
  "body": new EditorProps({ draggable: false, droppable: true, dragType:"body"}),
  "br": new EditorProps({ dragType:"br"}),
  "button": new EditorProps({ dragType:"button"}),
  "canvas": new EditorProps({ dragType:"canvas"}),
  "caption": new EditorProps({ droppable: true, dragType:"caption"}),
  "cite": new EditorProps({ droppable: true, dragType:"cite"}),
  "code": new EditorProps({ droppable: true, dragType:"code"}),
  "col": new EditorProps({ dragType:"col"}),
  "colgroup": new EditorProps({ droppable: true, dropTypes: "col", dragType:"colgroup"}),
  "data": new EditorProps({ droppable: true, dragType:"data"}),
  "datalist": new EditorProps({ droppable: true, dragType:"datalist"}),
  "dd": new EditorProps({ dragType:"dd"}),
  "del": new EditorProps({ droppable: true, dragType:"del"}),
  "details": new EditorProps({ droppable: true, dragType:"details"}),
  "dfn": new EditorProps({ droppable: true, dragType:"dfn"}),
  "dialog": new EditorProps({ droppable: true, dragType:"dialog"}),
  "div": new EditorProps({ droppable: true, dragType:"div"}),
  "dl": new EditorProps({ droppable: true, dropTypes: "dl,dt", dragType:"dl"}),
  "dt": new EditorProps({ droppable: true, dragType:"dt"}),
  "em": new EditorProps({ droppable: true, dragType:"em"}),
  "embed": new EditorProps({ dragType:"embed"}),
  "fieldset": new EditorProps({ droppable: true, dragType:"fieldset"}),
  "figcaption": new EditorProps({ droppable: true, dragType:"figcaption"}),
  "figure": new EditorProps({ droppable: true, dragType:"figure"}),
  "footer": new EditorProps({ droppable: true, dragType:"footer"}),
  "form": new EditorProps({ droppable: true, dragType:"form"}),
  "h1": new EditorProps({ droppable: true, dragType:"h1"}),
  "h2": new EditorProps({ droppable: true, dragType:"h2"}),
  "h3": new EditorProps({ droppable: true, dragType:"h3"}),
  "h4": new EditorProps({ droppable: true, dragType:"h4"}),
  "h5": new EditorProps({ droppable: true, dragType:"h5"}),
  "h6": new EditorProps({ droppable: true, dragType:"h6"}),
  "head": new EditorProps({ draggable: false, droppable: true, dragType:"head"}),
  "header": new EditorProps({ droppable: true, dragType:"header"}),
  "hgroup": new EditorProps({ droppable: true, dragType:"hgroup"}),
  "hr": new EditorProps({ dragType:"hr"}),
  "html": new EditorProps({ draggable: false, dragType:"html"}),
  "i": new EditorProps({ droppable: true, dragType:"i"}),
  "iframe": new EditorProps({ droppable: true, dragType:"iframe"}),
  "img": new EditorProps({ dragType:"img"}),
  "input": new EditorProps({ dragType:"input"}),
  "ins": new EditorProps({ droppable: true, dragType:"ins"}),
  "kbd": new EditorProps({ droppable: true, dragType:"kbd"}),
  "keygen": new EditorProps({ droppable: true, dragType:"keygen"}),
  "label": new EditorProps({ droppable: true, dragType:"label"}),
  "legend": new EditorProps({ droppable: true, dragType:"legend"}),
  "li": new EditorProps({ droppable: true, dragType:"li"}),
  "link": new EditorProps({ dragType:"link"}),
  "main": new EditorProps({ droppable: true, dragType:"main"}),
  "map": new EditorProps({ droppable: true, dragType:"map"}),
  "mark": new EditorProps({ droppable: true, dragType:"mark"}),
  "menu": new EditorProps({ droppable: true, dragType:"menu"}),
  "menuitem": new EditorProps({ dragType:"menuitem"}),
  "meta": new EditorProps({ dragType:"meta"}),
  "meter": new EditorProps({ droppable: true, dragType:"meter"}),
  "nav": new EditorProps({ droppable: true, dragType:"nav"}),
  "noscript": new EditorProps({ droppable: true, dragType:"noscript"}),
  "object": new EditorProps({ droppable: true, dragType:"object"}),
  "ol": new EditorProps({ droppable: true, dropTypes: "li,ol,ul", dragType:"ol"}),
  "optgroup": new EditorProps({ droppable: true, dropTypes: "option", dragType:"optgroup"}),
  "option": new EditorProps({ dragType:"option"}),
  "output": new EditorProps({ droppable: true, dragType:"output"}),
  "p": new EditorProps({ droppable: true, dragType:"p"}),
  "param": new EditorProps({ dragType:"param"}),
  "picture": new EditorProps({ droppable: true, dropTypes: "source,img", dragType:"picture"}),
  "pre": new EditorProps({ droppable: true, dragType:"pre"}),
  "progress": new EditorProps({ droppable: true, dragType:"progress"}),
  "q": new EditorProps({ droppable: true, dragType:"q"}),
  "rp": new EditorProps({ droppable: true, dragType:"rp"}),
  "rt": new EditorProps({ droppable: true, dragType:"rt"}),
  "ruby": new EditorProps({ droppable: true, dragType:"ruby"}),
  "s": new EditorProps({ droppable: true, dragType:"s"}),
  "samp": new EditorProps({ droppable: true, dragType:"samp"}),
  "script": new EditorProps({ dragType:"script"}),
  "section": new EditorProps({ droppable: true, dragType:"section"}),
  "select": new EditorProps({ droppable: true, dropTypes: "option,optgroup", dragType:"select"}),
  "small": new EditorProps({ droppable: true, dragType:"small"}),
  "source": new EditorProps({ dragType:"source"}),
  "span": new EditorProps({ droppable: true, dragType:"span"}),
  "strong": new EditorProps({ droppable: true, dragType:"strong"}),
  "style": new EditorProps({ dragType:"style"}),
  "sub": new EditorProps({ droppable: true, dragType:"sub"}),
  "summary": new EditorProps({ droppable: true, dragType:"summary"}),
  "sup": new EditorProps({ droppable: true, dragType:"sup"}),
  "table": new EditorProps({ droppable: true, dropTypes: "caption,colgroup,thead,tfoot,tbody,tr", dragType:"table"}),
  "tbody": new EditorProps({ droppable: true, dropTypes: "tr", dragType:"tbody"}),
  "td": new EditorProps({ droppable: true, dragType:"td"}),
  "textarea": new EditorProps({ dragType:"textarea"}),
  "tfoot": new EditorProps({ droppable: true, dropTypes: "tr", dragType:"tfoot"}),
  "th": new EditorProps({ droppable: true, dragType:"th"}),
  "thead": new EditorProps({ droppable: true, dropTypes: "tr", dragType:"thead"}),
  "time": new EditorProps({ droppable: true, dragType:"time"}),
  "title": new EditorProps({ dragType:"title"}),
  "tr": new EditorProps({ droppable: true, dropTypes: "td,th", dragType:"tr"}),
  "track": new EditorProps({ dragType:"track"}),
  "u": new EditorProps({ droppable: true, dragType:"u"}),
  "ul": new EditorProps({ droppable: true, dropTypes: "li,ol,ul", dragType:"ul"}),
  "var": new EditorProps({ droppable: true, dragType:"var"}),
  "video": new EditorProps({ droppable: true, dragType:"video"}),
  "wbr": new EditorProps({ dragType:"wbr" })
}
