// Export each SUI component as a loader function.
//
// Components which have been included explicitly in other files will be loaded in the main bundle.
// Components which are only rendered in, eg, <Oak.Pages> will be dynamically loaded automatically on first access.
//
export function SUIComponent(callback){ require.ensure([], () => callback(require("./SUI/SUIComponent"))) };
export function Accordion(callback){ require.ensure([], () => callback(require("./SUI/Accordion.jsx"))) };
export function Ad(callback){ require.ensure([], () => callback(require("./SUI/Ad"))) };
export function Button(callback){ require.ensure([], () => callback(require("./SUI/Button"))) };
export function Buttons(callback){ require.ensure([], () => callback(require("./SUI/Buttons"))) };
export function Breadcrumb(callback){ require.ensure([], () => callback(require("./SUI/Breadcrumb"))) };
export function Card(callback){ require.ensure([], () => callback(require("./SUI/Card"))) };
export function Cards(callback){ require.ensure([], () => callback(require("./SUI/Cards"))) };
export function Checkbox(callback){ require.ensure([], () => callback(require("./SUI/Checkbox"))) };
export function Column(callback){ require.ensure([], () => callback(require("./SUI/Column"))) };
export function Comment(callback){ require.ensure([], () => callback(require("./SUI/Comment"))) };
export function Comments(callback){ require.ensure([], () => callback(require("./SUI/Comments"))) };
export function Content(callback){ require.ensure([], () => callback(require("./SUI/Content"))) };
export function Conditional(callback){ require.ensure([], () => callback(require("./SUI/Conditional"))) };
export function Container(callback){ require.ensure([], () => callback(require("./SUI/Container"))) };
export function CountryMap(callback){ require.ensure([], () => callback(require("./SUI/CountryMap"))) };
export function Description(callback){ require.ensure([], () => callback(require("./SUI/Description"))) };
export function Dimmer(callback){ require.ensure([], () => callback(require("./SUI/Dimmer"))) };
export function Divider(callback){ require.ensure([], () => callback(require("./SUI/Divider"))) };
export function Dropdown(callback){ require.ensure([], () => callback(require("./SUI/Dropdown"))) };
export function ElementBuffer(callback){ require.ensure([], () => callback(require("./SUI/ElementBuffer"))) };
export function Embed(callback){ require.ensure([], () => callback(require("./SUI/Embed"))) };
export function Feed(callback){ require.ensure([], () => callback(require("./SUI/Feed"))) };
export function FeedEvent(callback){ require.ensure([], () => callback(require("./SUI/FeedEvent"))) };
export function Field(callback){ require.ensure([], () => callback(require("./SUI/Field"))) };
export function Fields(callback){ require.ensure([], () => callback(require("./SUI/Fields"))) };
export function Flag(callback){ require.ensure([], () => callback(require("./SUI/Flag"))) };
export function Form(callback){ require.ensure([], () => callback(require("./SUI/Form"))) };
export function Grid(callback){ require.ensure([], () => callback(require("./SUI/Grid"))) };
export function Header(callback){ require.ensure([], () => callback(require("./SUI/Header"))) };
export function Icon(callback){ require.ensure([], () => callback(require("./SUI/Icon"))) };
export function Image(callback){ require.ensure([], () => callback(require("./SUI/Image"))) };
export function Images(callback){ require.ensure([], () => callback(require("./SUI/Images"))) };
export function Input(callback){ require.ensure([], () => callback(require("./SUI/Input"))) };
export function Item(callback){ require.ensure([], () => callback(require("./SUI/Item"))) };
export function Items(callback){ require.ensure([], () => callback(require("./SUI/Items"))) };
export function Label(callback){ require.ensure([], () => callback(require("./SUI/Label"))) };
export function Labels(callback){ require.ensure([], () => callback(require("./SUI/Labels"))) };
export function List(callback){ require.ensure([], () => callback(require("./SUI/List"))) };
export function ListItem(callback){ require.ensure([], () => callback(require("./SUI/ListItem"))) };
export function Loader(callback){ require.ensure([], () => callback(require("./SUI/Loader"))) };
export function Menu(callback){ require.ensure([], () => callback(require("./SUI/Menu"))) };
export function MenuHeader(callback){ require.ensure([], () => callback(require("./SUI/MenuHeader"))) };
export function MenuItem(callback){ require.ensure([], () => callback(require("./SUI/MenuItem"))) };
export function Message(callback){ require.ensure([], () => callback(require("./SUI/Message"))) };
export function Meta(callback){ require.ensure([], () => callback(require("./SUI/Meta"))) };
export function Modal(callback){ require.ensure([], () => callback(require("./SUI/Modal"))) };
export function Nag(callback){ require.ensure([], () => callback(require("./SUI/Nag"))) };
export function Popup(callback){ require.ensure([], () => callback(require("./SUI/Popup"))) };
export function Pusher(callback){ require.ensure([], () => callback(require("./SUI/Pusher"))) };
export function Progress(callback){ require.ensure([], () => callback(require("./SUI/Progress"))) };
export function RadioButton(callback){ require.ensure([], () => callback(require("./SUI/RadioButton"))) };
export function RadioGroup(callback){ require.ensure([], () => callback(require("./SUI/RadioGroup"))) };
export function Rail(callback){ require.ensure([], () => callback(require("./SUI/Rail"))) };
export function Rating(callback){ require.ensure([], () => callback(require("./SUI/Rating"))) };
export function Row(callback){ require.ensure([], () => callback(require("./SUI/Row"))) };
export function Reveal(callback){ require.ensure([], () => callback(require("./SUI/Reveal"))) };
export function Shape(callback){ require.ensure([], () => callback(require("./SUI/Shape"))) };
export function Side(callback){ require.ensure([], () => callback(require("./SUI/Side"))) };
export function Sidebar(callback){ require.ensure([], () => callback(require("./SUI/Sidebar"))) };
export function Search(callback){ require.ensure([], () => callback(require("./SUI/Search"))) };
export function Segment(callback){ require.ensure([], () => callback(require("./SUI/Segment"))) };
export function Segments(callback){ require.ensure([], () => callback(require("./SUI/Segments"))) };
export function Statistic(callback){ require.ensure([], () => callback(require("./SUI/Statistic"))) };
export function Statistics(callback){ require.ensure([], () => callback(require("./SUI/Statistics"))) };
export function Step(callback){ require.ensure([], () => callback(require("./SUI/Step"))) };
export function Steps(callback){ require.ensure([], () => callback(require("./SUI/Steps"))) };
export function Sticky(callback){ require.ensure([], () => callback(require("./SUI/Sticky"))) };
export function Stub(callback){ require.ensure([], () => callback(require("./SUI/Stub"))) };
export function Subheader(callback){ require.ensure([], () => callback(require("./SUI/Subheader"))) };
export function Submenu(callback){ require.ensure([], () => callback(require("./SUI/Submenu"))) };
export function Tab(callback){ require.ensure([], () => callback(require("./SUI/Tab"))) };
export function Tabbar(callback){ require.ensure([], () => callback(require("./SUI/Tabbar"))) };
export function Table(callback){ require.ensure([], () => callback(require("./SUI/Table"))) };
export function Tabs(callback){ require.ensure([], () => callback(require("./SUI/Tabs"))) };
export function Title(callback){ require.ensure([], () => callback(require("./SUI/Title"))) };
export function Toggle(callback){ require.ensure([], () => callback(require("./SUI/Toggle"))) };

// Export all as a lump.
export default {...exports};
